# Generated by Django 3.0.7 on 2020-09-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='word',
        ),
    ]
