# Generated by Django 3.0.7 on 2020-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_remove_boardmodel_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='keyword',
            field=models.TextField(default=99),
            preserve_default=False,
        ),
    ]
